"""Relationships tables

Revision ID: b8e1de0f53d8
Revises: 6a76ac9f06d4
Create Date: 2022-04-02 14:28:19.332379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e1de0f53d8'
down_revision = '6a76ac9f06d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('buyer_id', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('card_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payments', 'buyers', ['buyer_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'cards', ['card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'card_id')
    op.drop_column('payments', 'buyer_id')
    # ### end Alembic commands ###
